### ISSUE TITLE
Error: " avr/interrupt.h: No such file or directory"

### ISSUE THREAD

**Issue by aspia** [kounch/homebridge_mitsubishi_ir_arduino#1]
Can't get past this issue trying to compile. I have a NodeMCU v2  I would like to control Heatpump through homebridge/homekit. I have set SS_MAX_RX_BUFF to 256. Google has neither a good answer for this. Any suggestion how to get past this point?

![skjermbilde 2018-08-31 kl 15 21 46](https://user-images.githubusercontent.com/12182970/44914891-c383d600-ad31-11e8-87c8-aee5444fcdd5.png)

**Comment by kounch** [comment]
It cannot compile with hour hardware. `avr/interrupt.h` is an Atmel AVR specific library, used by the code that i obtained from here:
https://github.com/r45635/HVAC-IR-Control

My project was designed to use Arduino compatible hardware which, optionally is connected to an ESP8266 to have WiFi access, but the hardware you are using doesn't have an Atmel chip, instead it is a ESP8266.

To adapt it to your hardware, i think that you could have to look at their example for ESP8266:
https://github.com/r45635/HVAC-IR-Control/tree/master/HVAC_ESP8266

And then see if you can rewrite homebridge_mitsubishi_ir_arduino.ino to fit your needs, removing all Arduino exclusive libraries (`IRremote2.h, ESP8266.h, SoftwareSerial.h, SimpleDHT.h`) and using some similar libraries but for ESP8266.

**Comment by aspia** [comment]
Ah, thank you. Will give it a go

**Comment by Zigia** [comment]
So ware you able to do it? And if you did can you paste the rewriten homebridge_mitsubishi_ir_arduino.ino? Thank you
